language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-bh-yeoman-wp' ]; then cd .. && eval "mv $currentfolder generator-bh-yeoman-wp" && cd generator-bh-yeoman-wp; fi

